const prettierConfig = require('@gbrachetta/prettier-config');

module.exports = {
  env: {
    browser: true,
    commonjs: true,
    es2021: true,
    jest: true,
    node: true,
  },
  extends: [
    'eslint:recommended',
    'airbnb',
    'airbnb/hooks',
    'plugin:react/recommended',
    'plugin:import/errors',
    'plugin:import/typescript',
    'plugin:import/warnings',
    'plugin:jsx-a11y/recommended',
    'plugin:react-hooks/recommended',
    'plugin:sort/recommended',
    'prettier',
  ],
  globals: {
    Atomics: 'readonly',
    SharedArrayBuffer: 'readonly',
  },
  ignorePatterns: ['node_modules/'],
  parser: '@typescript-eslint/parser',
  parserOptions: {
    ecmaFeatures: {
      jsx: true,
    },
    ecmaVersion: 11,
    sourceType: 'module',
  },
  plugins: [
    'prettier',
    'react',
    'react-hooks',
    'jsx-a11y',
    'simple-import-sort',
    'sort-keys-fix',
    'sort',
    '@typescript-eslint',
  ],
  root: true,
  rules: {
    'arrow-body-style': 0,
    'arrow-spacing': 1,
    camelcase: 1,
    'class-methods-use-this': 0,
    'consistent-return': 0,
    'guard-for-in': 1,
    'import/extensions': [
      'error',
      'ignorePackages',
      {
        js: 'never',
        jsx: 'never',
        ts: 'never',
        tsx: 'never',
      },
    ],
    'import/newline-after-import': 1,
    'import/no-dynamic-require': 0,
    'import/no-extraneous-dependencies': 0,
    'import/no-named-as-default': 0,
    'import/no-unresolved': 2,
    'import/no-webpack-loader-syntax': 0,
    'import/order': [
      'warn',
      {
        alphabetize: {
          caseInsensitive: true,
          order: 'ignore',
        },
        groups: ['builtin', 'external', 'parent', 'sibling', 'index'],
        'newlines-between': 'always',
      },
    ],
    'import/prefer-default-export': 1,
    'jsx-a11y/aria-props': 2,
    'jsx-a11y/click-events-have-key-events': 0,
    'jsx-a11y/heading-has-content': 0,
    'jsx-a11y/label-has-associated-control': 0,
    'jsx-a11y/mouse-events-have-key-events': 1,
    'jsx-a11y/no-noninteractive-element-interactions': 0,
    'jsx-a11y/no-onchange': 0,
    'jsx-a11y/no-static-element-interactions': 1,
    'jsx-a11y/role-has-required-aria-props': 2,
    'jsx-a11y/role-supports-aria-props': 2,
    'max-len': 0,
    'newline-per-chained-call': 1,
    'no-confusing-arrow': 0,
    'no-console': 1,
    'no-restricted-syntax': 1,
    'no-trailing-spaces': 2,
    'no-unused-vars': 1,
    'no-use-before-define': 1,
    'no-var': 2,
    'padding-line-between-statements': [
      1,
      {
        blankLine: 'always',
        next: ['return', 'export', 'function', 'block-like'],
        prev: '*',
      },
      {
        blankLine: 'always',
        next: '*',
        prev: ['case', 'default', 'directive', 'const', 'let', 'block-like'],
      },
      {
        blankLine: 'any',
        next: ['let'],
        prev: ['let'],
      },
      {
        blankLine: 'any',
        next: ['const'],
        prev: ['const'],
      },
    ],
    'prefer-template': 2,
    'prettier/prettier': [2, prettierConfig],
    'react/button-has-type': 1,
    'react/destructuring-assignment': 1,
    'react/display-name': 1,
    'react/forbid-prop-types': 0,
    'react/function-component-definition': [
      'error',
      {
        defaultProps: 'arrow-function',
        destructuring: 'always',
        jsx: 'preserve',
        namedComponents: ['arrow-function', 'function-declaration'],
        unnamedComponents: 'arrow-function',
      },
    ],
    'react/jsx-closing-tag-location': 0,
    'react/jsx-filename-extension': [
      1,
      {
        extensions: ['.js', '.jsx', '.ts', '.tsx'],
      },
    ],
    'react/jsx-first-prop-new-line': [2, 'multiline'],
    'react/jsx-key': 1,
    'react/jsx-no-target-blank': 1,
    'react/jsx-props-no-spreading': [
      1,
      {
        exceptions: ['Component'],
      },
    ],
    'react/jsx-sort-props': 1,
    'react/jsx-uses-vars': 2,
    'react/no-array-index-key': 1,
    'react/no-unescaped-entities': 0,
    'react/prop-types': [
      1,
      {
        ignore: ['Component', 'pageProps'],
      },
    ],
    'react/react-in-jsx-scope': 0,
    'react/require-default-props': 1,
    'react/self-closing-comp': 1,
    'react/sort-comp': 0,
    'react-hooks/rules-of-hooks': 2,
    'simple-import-sort/imports': 0,
    'sort/object-properties': 0,
    'sort-imports': [
      'warn',
      {
        allowSeparatedGroups: true,
        ignoreCase: true,
        ignoreDeclarationSort: true,
        ignoreMemberSort: false,
        memberSyntaxSortOrder: ['all', 'multiple', 'single', 'none'],
      },
    ],
    'sort-keys-fix/sort-keys-fix': [
      1,
      'asc',
      {
        natural: true,
      },
    ],
    'space-before-blocks': 1,
    'space-before-function-paren': 1,
    'spaced-comment': [1, 'always'],
  },
  settings: {
    'import/resolver': {
      node: {
        extensions: ['.js', '.jsx', '.ts', '.tsx'],
      },
    },
    react: {
      version: 'detect',
    },
  },
};
